In [88]:
import pandas as pd
import os
import chardet

In [89]:
# 1. Load the BEA county GDP data
CAGDP1 = "/Users/koacow/BOSTON UNIVERSITY Dropbox/Ngoc Duy Khoa Cao/GLOB~S/Data/U.S. County Data/BEA_COUNTY_1969_2023/CAGDP1__ALL_AREAS_2001_2023.csv"
CAGDP1_encoding = 'utf-8'
with open(CAGDP1, 'rb') as file:
    result = chardet.detect(file.read())
    CAGDP1_encoding = result['encoding']
CAGDP1_df = pd.read_csv(CAGDP1, dtype={'GeoFIPS': str}, encoding=CAGDP1_encoding, na_values=['(NA)', '(N/A)'])
CAGDP1_df = CAGDP1_df.rename(columns={
    "GeoFIPS": "FIPS5",
    "GeoName": "geographic_area_name"
})
CAGDP1_df = CAGDP1_df[:-4]
CAGDP1_df

,FIPS5,geographic_area_name,Region,TableName,LineCode,IndustryClassification,Description,Unit,2001,2002,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,"""00000""",United States,,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,14230726000,14472712000,...,1.826171e+10,1.879962e+10,1.914167e+10,1.961210e+10,2.019390e+10,2.071567e+10,20267585000,21494798000,22034828000,22671096000
1,"""00000""",United States,,CAGDP1,2.0,...,Chain-type quantity indexes for real GDP,Quantity index,72.561,73.795,...,9.311500e+01,9.585700e+01,9.760100e+01,1.000000e+02,1.029670e+02,1.056270e+02,103.342,109.600,112.353,115.597
2,"""00000""",United States,,CAGDP1,3.0,...,Current-dollar GDP (thousands of current dolla...,Thousands of dollars,10581929000,10929108000,...,1.760814e+10,1.829502e+10,1.880491e+10,1.961210e+10,2.065652e+10,2.153998e+10,21354105000,23681171000,26006893000,27720709000
3,"""01000""",Alabama,5,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,168448296,172430379,...,2.060700e+08,2.089503e+08,2.128628e+08,2.166155e+08,2.208088e+08,2.252728e+08,222288753,233726620,238556458,245354674
4,"""01000""",Alabama,5,CAGDP1,2.0,...,Chain-type quantity indexes for real GDP,Quantity index,77.764,79.602,...,9.513200e+01,9.646100e+01,9.826800e+01,1.000000e+02,1.019360e+02,1.039970e+02,102.619,107.899,110.129,113.267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9529,"""97000""",Rocky Mountain,7,CAGDP1,2.0,...,Chain-type quantity indexes for real GDP,Quantity index,66.507,67.417,...,9.065100e+01,9.415700e+01,9.623700e+01,1.000000e+02,1.045590e+02,1.095580e+02,109.182,116.884,120.681,125.650
9530,"""97000""",Rocky Mountain,7,CAGDP1,3.0,...,Current-dollar GDP (thousands of current dolla...,Thousands of dollars,338172137,347931550,...,6.021310e+08,6.218900e+08,6.410470e+08,6.813101e+08,7.305677e+08,7.763302e+08,780157535,880955513,986528188,1057159025
9531,"""98000""",Far West,8,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,2463451014,2514956943,...,3.360531e+09,3.516768e+09,3.629300e+09,3.797440e+09,3.956948e+09,4.115306e+09,4055843532,4352482955,4411936147,4525827912
9532,"""98000""",Far West,8,CAGDP1,2.0,...,Chain-type quantity indexes for real GDP,Quantity index,64.871,66.228,...,8.849500e+01,9.260900e+01,9.557200e+01,1.000000e+02,1.042000e+02,1.083710e+02,106.805,114.616,116.182,119.181
9533,"""98000""",Far West,8,CAGDP1,3.0,...,Current-dollar GDP (thousands of current dolla...,Thousands of dollars,1880381028,1945882821,...,3.240456e+09,3.434111e+09,3.576785e+09,3.797440e+09,4.026579e+09,4.258456e+09,4260931225,4741363266,5098918682,5421427913

In [90]:
# 1.2 Filter the data to only keep rows with 'Real GDP (thousands of chained 2017 dollars)' in the 'Description' column
CAGDP1_df = CAGDP1_df[CAGDP1_df['Description'].str.contains("Real GDP")]
CAGDP1_df

,FIPS5,geographic_area_name,Region,TableName,LineCode,IndustryClassification,Description,Unit,2001,2002,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,"""00000""",United States,,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,14230726000,14472712000,...,1.826171e+10,1.879962e+10,1.914167e+10,1.961210e+10,2.019390e+10,2.071567e+10,20267585000,21494798000,22034828000,22671096000
3,"""01000""",Alabama,5,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,168448296,172430379,...,2.060700e+08,2.089503e+08,2.128628e+08,2.166155e+08,2.208088e+08,2.252728e+08,222288753,233726620,238556458,245354674
6,"""01001""","Autauga, AL",5,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,1041239,1080135,...,1.629762e+06,1.765826e+06,1.846256e+06,1.762558e+06,1.787534e+06,1.740015e+06,1746979,1736001,1895751,1945909
9,"""01003""","Baldwin, AL",5,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,4470762,4699162,...,6.455247e+06,6.757534e+06,7.113177e+06,7.382558e+06,7.758980e+06,8.145105e+06,8109210,8706236,9145388,9435720
12,"""01005""","Barbour, AL",5,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,849519,834951,...,7.996430e+05,7.810550e+05,7.707500e+05,7.617610e+05,7.740760e+05,7.620900e+05,732151,753330,744850,715994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9519,"""94000""",Plains,4,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,910419433,930798771,...,1.202107e+09,1.227189e+09,1.237736e+09,1.250759e+09,1.274026e+09,1.288476e+09,1262663108,1330505923,1354128628,1388150705
9522,"""95000""",Southeast,5,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,3118856908,3195086660,...,3.902765e+09,4.011954e+09,4.102067e+09,4.210089e+09,4.315633e+09,4.423103e+09,4345697448,4641104513,4802786205,4952758909
9525,"""96000""",Southwest,6,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,1446381479,1480277662,...,2.140042e+09,2.229860e+09,2.235959e+09,2.286161e+09,2.385042e+09,2.466719e+09,2428217260,2569595986,2660434410,2838599111
9528,"""97000""",Rocky Mountain,7,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,453118482,459318533,...,6.176178e+08,6.414991e+08,6.556726e+08,6.813101e+08,7.123721e+08,7.464288e+08,743870716,796343098,822215229,856063087
9531,"""98000""",Far West,8,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,2463451014,2514956943,...,3.360531e+09,3.516768e+09,3.629300e+09,3.797440e+09,3.956948e+09,4.115306e+09,4055843532,4352482955,4411936147,4525827912

In [91]:
# 1.3 Remove the quotes from the FIPS5 column
CAGDP1_df['FIPS5'] = CAGDP1_df['FIPS5'].str.replace('"', '', regex=False)
CAGDP1_df

/var/folders/zx/x6hb1_p95p33hh3235qrnlqm0000gn/T/ipykernel_98953/913014132.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  CAGDP1_df['FIPS5'] = CAGDP1_df['FIPS5'].str.replace('"', '', regex=False)

,FIPS5,geographic_area_name,Region,TableName,LineCode,IndustryClassification,Description,Unit,2001,2002,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,00000,United States,,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,14230726000,14472712000,...,1.826171e+10,1.879962e+10,1.914167e+10,1.961210e+10,2.019390e+10,2.071567e+10,20267585000,21494798000,22034828000,22671096000
3,01000,Alabama,5,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,168448296,172430379,...,2.060700e+08,2.089503e+08,2.128628e+08,2.166155e+08,2.208088e+08,2.252728e+08,222288753,233726620,238556458,245354674
6,01001,"Autauga, AL",5,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,1041239,1080135,...,1.629762e+06,1.765826e+06,1.846256e+06,1.762558e+06,1.787534e+06,1.740015e+06,1746979,1736001,1895751,1945909
9,01003,"Baldwin, AL",5,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,4470762,4699162,...,6.455247e+06,6.757534e+06,7.113177e+06,7.382558e+06,7.758980e+06,8.145105e+06,8109210,8706236,9145388,9435720
12,01005,"Barbour, AL",5,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,849519,834951,...,7.996430e+05,7.810550e+05,7.707500e+05,7.617610e+05,7.740760e+05,7.620900e+05,732151,753330,744850,715994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9519,94000,Plains,4,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,910419433,930798771,...,1.202107e+09,1.227189e+09,1.237736e+09,1.250759e+09,1.274026e+09,1.288476e+09,1262663108,1330505923,1354128628,1388150705
9522,95000,Southeast,5,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,3118856908,3195086660,...,3.902765e+09,4.011954e+09,4.102067e+09,4.210089e+09,4.315633e+09,4.423103e+09,4345697448,4641104513,4802786205,4952758909
9525,96000,Southwest,6,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,1446381479,1480277662,...,2.140042e+09,2.229860e+09,2.235959e+09,2.286161e+09,2.385042e+09,2.466719e+09,2428217260,2569595986,2660434410,2838599111
9528,97000,Rocky Mountain,7,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,453118482,459318533,...,6.176178e+08,6.414991e+08,6.556726e+08,6.813101e+08,7.123721e+08,7.464288e+08,743870716,796343098,822215229,856063087
9531,98000,Far West,8,CAGDP1,1.0,...,Real GDP (thousands of chained 2017 dollars),Thousands of chained 2017 dollars,2463451014,2514956943,...,3.360531e+09,3.516768e+09,3.629300e+09,3.797440e+09,3.956948e+09,4.115306e+09,4055843532,4352482955,4411936147,4525827912

In [92]:
# 1.4 Drop the irrelevant columns
CAGDP1_df = CAGDP1_df.drop(columns=['LineCode','Region', 'Description', 'Unit', 'IndustryClassification', 'TableName'])
years_to_keep = [str(year) for year in range(2001, 2023)]
CAGDP1_df = CAGDP1_df[['FIPS5', 'geographic_area_name'] + years_to_keep]
CAGDP1_df

,FIPS5,geographic_area_name,2001,2002,2003,2004,2005,2006,2007,2008,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,00000,United States,14230726000,14472712000,14877312000,15449757000,15987957000,16433148000,16762445000,16781485000,...,1.781217e+10,1.826171e+10,1.879962e+10,1.914167e+10,1.961210e+10,2.019390e+10,2.071567e+10,20267585000,21494798000,22034828000
3,01000,Alabama,168448296,172430379,178039962,189913745,197246483,199923857,202025481,200967427,...,2.069629e+08,2.060700e+08,2.089503e+08,2.128628e+08,2.166155e+08,2.208088e+08,2.252728e+08,222288753,233726620,238556458
6,01001,"Autauga, AL",1041239,1080135,1111465,1283522,1297102,1384119,1407555,1283751,...,1.618151e+06,1.629762e+06,1.765826e+06,1.846256e+06,1.762558e+06,1.787534e+06,1.740015e+06,1746979,1736001,1895751
9,01003,"Baldwin, AL",4470762,4699162,4987728,5488860,6091919,6264024,6447685,6230645,...,6.314704e+06,6.455247e+06,6.757534e+06,7.113177e+06,7.382558e+06,7.758980e+06,8.145105e+06,8109210,8706236,9145388
12,01005,"Barbour, AL",849519,834951,858421,930345,930410,908655,878961,826389,...,8.410370e+05,7.996430e+05,7.810550e+05,7.707500e+05,7.617610e+05,7.740760e+05,7.620900e+05,732151,753330,744850
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9519,94000,Plains,910419433,930798771,965431834,1002489691,1032697339,1047757569,1071799659,1092075727,...,1.167911e+09,1.202107e+09,1.227189e+09,1.237736e+09,1.250759e+09,1.274026e+09,1.288476e+09,1262663108,1330505923,1354128628
9522,95000,Southeast,3118856908,3195086660,3312051560,3473548695,3634909922,3726096703,3752274330,3738925147,...,3.828030e+09,3.902765e+09,4.011954e+09,4.102067e+09,4.210089e+09,4.315633e+09,4.423103e+09,4345697448,4641104513,4802786205
9525,96000,Southwest,1446381479,1480277662,1510596470,1592175931,1648724344,1754561799,1832803433,1833232871,...,2.075731e+09,2.140042e+09,2.229860e+09,2.235959e+09,2.286161e+09,2.385042e+09,2.466719e+09,2428217260,2569595986,2660434410
9528,97000,Rocky Mountain,453118482,459318533,467703707,484373456,511144300,533204603,555985280,563305602,...,5.947207e+08,6.176178e+08,6.414991e+08,6.556726e+08,6.813101e+08,7.123721e+08,7.464288e+08,743870716,796343098,822215229
9531,98000,Far West,2463451014,2514956943,2609835821,2705895007,2835774939,2947201499,3026963051,3056662307,...,3.249258e+09,3.360531e+09,3.516768e+09,3.629300e+09,3.797440e+09,3.956948e+09,4.115306e+09,4055843532,4352482955,4411936147

In [93]:
# 2. Conver the table from wide to long format
CAGDP1_df = CAGDP1_df.melt(id_vars=['FIPS5', 'geographic_area_name'], 
                            var_name='year',
                            value_name='rgdp')
CAGDP1_df['year'] = CAGDP1_df['year'].astype(int)
CAGDP1_df['rgdp'] = CAGDP1_df['rgdp'].astype(float)
CAGDP1_df = CAGDP1_df.sort_values(by=['FIPS5', 'year']).reset_index(drop=True)
CAGDP1_df

        FIPS5 geographic_area_name  year          rgdp
0       00000        United States  2001  1.423073e+10
1       00000        United States  2002  1.447271e+10
2       00000        United States  2003  1.487731e+10
3       00000        United States  2004  1.544976e+10
4       00000        United States  2005  1.598796e+10
...       ...                  ...   ...           ...
69911   98000             Far West  2018  3.956948e+09
69912   98000             Far West  2019  4.115306e+09
69913   98000             Far West  2020  4.055844e+09
69914   98000             Far West  2021  4.352483e+09
69915   98000             Far West  2022  4.411936e+09

[69916 rows x 4 columns]

In [94]:
CAGDP1_df['year'].value_counts()

year
2001    3178
2002    3178
2021    3178
2020    3178
2019    3178
2018    3178
2017    3178
2016    3178
2015    3178
2014    3178
2013    3178
2012    3178
2011    3178
2010    3178
2009    3178
2008    3178
2007    3178
2006    3178
2005    3178
2004    3178
2003    3178
2022    3178
Name: count, dtype: int64

In [95]:
CAGDP1_df.isna().sum()

FIPS5                     0
geographic_area_name      0
year                      0
rgdp                    123
dtype: int64

In [96]:
# 3.1 Load the BEA county personal income data
CAINC1 = "/Users/koacow/BOSTON UNIVERSITY Dropbox/Ngoc Duy Khoa Cao/GLOB~S/Data/U.S. County Data/BEA_COUNTY_1969_2023/CAINC1__ALL_AREAS_1969_2023.csv"
CAINC1_encoding = 'utf-8'
with open(CAINC1, 'rb') as file:
    result = chardet.detect(file.read())
    CAINC1_encoding = result['encoding']
CAINC1_df = pd.read_csv(CAINC1, dtype={"GeoFIPS": str}, encoding=CAINC1_encoding, na_values=['(NA)', '(N/A)'])
CAINC1_df = CAINC1_df.rename(columns={
    "GeoFIPS": "FIPS5",
    "GeoName": "geographic_area_name"
})
CAINC1_df = CAINC1_df[:-4]
CAINC1_df

,FIPS5,geographic_area_name,Region,TableName,LineCode,IndustryClassification,Description,Unit,1969,1970,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,"""00000""",United States,,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,791229000.0,855525000.0,...,1.477816e+10,1.546711e+10,1.588474e+10,1.665896e+10,1.751440e+10,1.834958e+10,1.960094e+10,2.140398e+10,2.207723e+10,2.338027e+10
1,"""00000""",United States,,CAINC1,2.0,...,Population (persons) 1/,Number of persons,201298000.0,203798722.0,...,3.192576e+08,3.218151e+08,3.243533e+08,3.266086e+08,3.285296e+08,3.302262e+08,3.315269e+08,3.320490e+08,3.332714e+08,3.349149e+08
2,"""00000""",United States,,CAINC1,3.0,...,Per capita personal income (dollars) 2/,Dollars,3931.0,4198.0,...,4.628900e+04,4.806200e+04,4.897400e+04,5.100600e+04,5.331100e+04,5.556700e+04,5.912300e+04,6.446000e+04,6.624400e+04,6.981000e+04
3,"""01000""",Alabama,5,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,9737715.0,10628318.0,...,1.794871e+08,1.874747e+08,1.908718e+08,1.979638e+08,2.056742e+08,2.151518e+08,2.307322e+08,2.549604e+08,2.622356e+08,2.769256e+08
4,"""01000""",Alabama,5,CAINC1,2.0,...,Population (persons) 1/,Number of persons,3440000.0,3449846.0,...,4.887757e+06,4.909177e+06,4.931579e+06,4.953096e+06,4.977088e+06,5.003778e+06,5.031864e+06,5.050380e+06,5.073903e+06,5.108468e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9595,"""97000""",Rocky Mountain,7,CAINC1,2.0,...,Population (persons) 1/,Number of persons,4943000.0,5037873.0,...,1.154137e+07,1.172357e+07,1.191766e+07,1.209562e+07,1.226921e+07,1.242802e+07,1.258342e+07,1.274133e+07,1.286578e+07,1.297694e+07
9596,"""97000""",Rocky Mountain,7,CAINC1,3.0,...,Per capita personal income (dollars) 2/,Dollars,3602.0,3956.0,...,4.470800e+04,4.616900e+04,4.647600e+04,4.876800e+04,5.164700e+04,5.464600e+04,5.814700e+04,6.459100e+04,6.822400e+04,7.152400e+04
9597,"""98000""",Far West,8,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,121725092.0,131575529.0,...,2.697505e+09,2.886096e+09,3.016423e+09,3.169741e+09,3.339906e+09,3.526757e+09,3.830200e+09,4.172952e+09,4.203822e+09,4.444680e+09
9598,"""98000""",Far West,8,CAINC1,2.0,...,Population (persons) 1/,Number of persons,26635000.0,27101402.0,...,5.465250e+07,5.520837e+07,5.573857e+07,5.617382e+07,5.647700e+07,5.666330e+07,5.677280e+07,5.647126e+07,5.641457e+07,5.637415e+07
9599,"""98000""",Far West,8,CAINC1,3.0,...,Per capita personal income (dollars) 2/,Dollars,4570.0,4855.0,...,4.935700e+04,5.227600e+04,5.411700e+04,5.642700e+04,5.913700e+04,6.224100e+04,6.746500e+04,7.389500e+04,7.451700e+04,7.884300e+04

In [97]:
# 3.2 Filter the data to only keep rows with 'Personal income (thousands of dollars)' in the 'Description' column
CAINC1_df = CAINC1_df[CAINC1_df['Description'].str.contains("Personal income")]
CAINC1_df

,FIPS5,geographic_area_name,Region,TableName,LineCode,IndustryClassification,Description,Unit,1969,1970,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,"""00000""",United States,,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,791229000.0,855525000.0,...,1.477816e+10,1.546711e+10,1.588474e+10,1.665896e+10,1.751440e+10,1.834958e+10,1.960094e+10,2.140398e+10,2.207723e+10,2.338027e+10
3,"""01000""",Alabama,5,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,9737715.0,10628318.0,...,1.794871e+08,1.874747e+08,1.908718e+08,1.979638e+08,2.056742e+08,2.151518e+08,2.307322e+08,2.549604e+08,2.622356e+08,2.769256e+08
6,"""01001""","Autauga, AL",5,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,69973.0,77712.0,...,2.036671e+06,2.145869e+06,2.222448e+06,2.290351e+06,2.371211e+06,2.477876e+06,2.655187e+06,2.911242e+06,2.974989e+06,3.202910e+06
9,"""01003""","Baldwin, AL",5,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,157191.0,172745.0,...,7.949643e+06,8.504769e+06,9.032772e+06,9.583207e+06,1.013930e+07,1.088089e+07,1.187004e+07,1.347689e+07,1.420527e+07,1.545608e+07
12,"""01005""","Barbour, AL",5,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,51130.0,57657.0,...,7.960380e+05,8.262520e+05,8.136370e+05,8.185090e+05,8.429070e+05,8.738490e+05,9.253990e+05,1.004726e+06,1.013459e+06,1.021034e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9585,"""94000""",Plains,4,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,59315639.0,64334104.0,...,9.663542e+08,9.972983e+08,1.010852e+09,1.043303e+09,1.093520e+09,1.134579e+09,1.212194e+09,1.330943e+09,1.394917e+09,1.464221e+09
9588,"""95000""",Southeast,5,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,138939401.0,152550037.0,...,3.326261e+09,3.493964e+09,3.598072e+09,3.786490e+09,3.978127e+09,4.190038e+09,4.478727e+09,4.951225e+09,5.153501e+09,5.491964e+09
9591,"""96000""",Southwest,6,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,56500512.0,62538485.0,...,1.766253e+09,1.800501e+09,1.801519e+09,1.919437e+09,2.046252e+09,2.155669e+09,2.273019e+09,2.519124e+09,2.671309e+09,2.848129e+09
9594,"""97000""",Rocky Mountain,7,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,17805758.0,19931406.0,...,5.159876e+08,5.412607e+08,5.538868e+08,5.898768e+08,6.336650e+08,6.791430e+08,7.316829e+08,8.229737e+08,8.777606e+08,9.281606e+08
9597,"""98000""",Far West,8,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,121725092.0,131575529.0,...,2.697505e+09,2.886096e+09,3.016423e+09,3.169741e+09,3.339906e+09,3.526757e+09,3.830200e+09,4.172952e+09,4.203822e+09,4.444680e+09

In [98]:
# 3.3 Remove the quotes from the FIPS5 column
CAINC1_df['FIPS5'] = CAINC1_df['FIPS5'].str.replace('"', '', regex=False)
CAINC1_df

/var/folders/zx/x6hb1_p95p33hh3235qrnlqm0000gn/T/ipykernel_98953/3035543071.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  CAINC1_df['FIPS5'] = CAINC1_df['FIPS5'].str.replace('"', '', regex=False)

,FIPS5,geographic_area_name,Region,TableName,LineCode,IndustryClassification,Description,Unit,1969,1970,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,00000,United States,,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,791229000.0,855525000.0,...,1.477816e+10,1.546711e+10,1.588474e+10,1.665896e+10,1.751440e+10,1.834958e+10,1.960094e+10,2.140398e+10,2.207723e+10,2.338027e+10
3,01000,Alabama,5,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,9737715.0,10628318.0,...,1.794871e+08,1.874747e+08,1.908718e+08,1.979638e+08,2.056742e+08,2.151518e+08,2.307322e+08,2.549604e+08,2.622356e+08,2.769256e+08
6,01001,"Autauga, AL",5,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,69973.0,77712.0,...,2.036671e+06,2.145869e+06,2.222448e+06,2.290351e+06,2.371211e+06,2.477876e+06,2.655187e+06,2.911242e+06,2.974989e+06,3.202910e+06
9,01003,"Baldwin, AL",5,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,157191.0,172745.0,...,7.949643e+06,8.504769e+06,9.032772e+06,9.583207e+06,1.013930e+07,1.088089e+07,1.187004e+07,1.347689e+07,1.420527e+07,1.545608e+07
12,01005,"Barbour, AL",5,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,51130.0,57657.0,...,7.960380e+05,8.262520e+05,8.136370e+05,8.185090e+05,8.429070e+05,8.738490e+05,9.253990e+05,1.004726e+06,1.013459e+06,1.021034e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9585,94000,Plains,4,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,59315639.0,64334104.0,...,9.663542e+08,9.972983e+08,1.010852e+09,1.043303e+09,1.093520e+09,1.134579e+09,1.212194e+09,1.330943e+09,1.394917e+09,1.464221e+09
9588,95000,Southeast,5,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,138939401.0,152550037.0,...,3.326261e+09,3.493964e+09,3.598072e+09,3.786490e+09,3.978127e+09,4.190038e+09,4.478727e+09,4.951225e+09,5.153501e+09,5.491964e+09
9591,96000,Southwest,6,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,56500512.0,62538485.0,...,1.766253e+09,1.800501e+09,1.801519e+09,1.919437e+09,2.046252e+09,2.155669e+09,2.273019e+09,2.519124e+09,2.671309e+09,2.848129e+09
9594,97000,Rocky Mountain,7,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,17805758.0,19931406.0,...,5.159876e+08,5.412607e+08,5.538868e+08,5.898768e+08,6.336650e+08,6.791430e+08,7.316829e+08,8.229737e+08,8.777606e+08,9.281606e+08
9597,98000,Far West,8,CAINC1,1.0,...,Personal income (thousands of dollars),Thousands of dollars,121725092.0,131575529.0,...,2.697505e+09,2.886096e+09,3.016423e+09,3.169741e+09,3.339906e+09,3.526757e+09,3.830200e+09,4.172952e+09,4.203822e+09,4.444680e+09

In [99]:
# 3.4 Drop the irrelevant columns
CAINC1_df = CAINC1_df.drop(columns=['LineCode','Region', 'Description', 'Unit', 'IndustryClassification', 'TableName'])
years_to_keep = [str(year) for year in range(1980, 2023)]
CAINC1_df = CAINC1_df[['FIPS5', 'geographic_area_name'] + years_to_keep]
CAINC1_df

,FIPS5,geographic_area_name,1980,1981,1982,1983,1984,1985,1986,1987,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,00000,United States,2.313972e+09,2.590995e+09,2.777640e+09,2.969333e+09,3.275415e+09,3.508482e+09,3.717756e+09,3.931800e+09,...,1.406328e+10,1.477816e+10,1.546711e+10,1.588474e+10,1.665896e+10,1.751440e+10,1.834958e+10,1.960094e+10,2.140398e+10,2.207723e+10
3,01000,Alabama,3.104437e+07,3.445417e+07,3.638463e+07,3.897885e+07,4.283800e+07,4.608582e+07,4.877721e+07,5.151437e+07,...,1.737207e+08,1.794871e+08,1.874747e+08,1.908718e+08,1.979638e+08,2.056742e+08,2.151518e+08,2.307322e+08,2.549604e+08,2.622356e+08
6,01001,"Autauga, AL",2.500670e+05,2.619350e+05,2.801880e+05,3.020170e+05,3.374590e+05,3.661730e+05,3.906850e+05,4.242530e+05,...,1.966036e+06,2.036671e+06,2.145869e+06,2.222448e+06,2.290351e+06,2.371211e+06,2.477876e+06,2.655187e+06,2.911242e+06,2.974989e+06
9,01003,"Baldwin, AL",6.159850e+05,7.173750e+05,7.590920e+05,8.446810e+05,9.397530e+05,1.047779e+06,1.114801e+06,1.177163e+06,...,7.534558e+06,7.949643e+06,8.504769e+06,9.032772e+06,9.583207e+06,1.013930e+07,1.088089e+07,1.187004e+07,1.347689e+07,1.420527e+07
12,01005,"Barbour, AL",1.600550e+05,1.792910e+05,1.869590e+05,2.008010e+05,2.297650e+05,2.447480e+05,2.643710e+05,2.797320e+05,...,7.990400e+05,7.960380e+05,8.262520e+05,8.136370e+05,8.185090e+05,8.429070e+05,8.738490e+05,9.253990e+05,1.004726e+06,1.013459e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9585,94000,Plains,1.657956e+08,1.874142e+08,1.996225e+08,2.092731e+08,2.330328e+08,2.460573e+08,2.574930e+08,2.703651e+08,...,9.293560e+08,9.663542e+08,9.972983e+08,1.010852e+09,1.043303e+09,1.093520e+09,1.134579e+09,1.212194e+09,1.330943e+09,1.394917e+09
9588,95000,Southeast,4.656072e+08,5.263681e+08,5.641356e+08,6.080920e+08,6.747303e+08,7.259868e+08,7.735962e+08,8.233712e+08,...,3.160320e+09,3.326261e+09,3.493964e+09,3.598072e+09,3.786490e+09,3.978127e+09,4.190038e+09,4.478727e+09,4.951225e+09,5.153501e+09
9591,96000,Southwest,2.102811e+08,2.454116e+08,2.697588e+08,2.877327e+08,3.149580e+08,3.393854e+08,3.499185e+08,3.578922e+08,...,1.656654e+09,1.766253e+09,1.800501e+09,1.801519e+09,1.919437e+09,2.046252e+09,2.155669e+09,2.273019e+09,2.519124e+09,2.671309e+09
9594,97000,Rocky Mountain,6.548995e+07,7.444397e+07,8.046508e+07,8.607868e+07,9.310238e+07,9.831771e+07,1.018407e+08,1.049705e+08,...,4.821154e+08,5.159876e+08,5.412607e+08,5.538868e+08,5.898768e+08,6.336650e+08,6.791430e+08,7.316829e+08,8.229737e+08,8.777606e+08
9597,98000,Far West,3.851640e+08,4.304527e+08,4.603515e+08,4.966219e+08,5.464271e+08,5.887235e+08,6.300058e+08,6.729482e+08,...,2.536152e+09,2.697505e+09,2.886096e+09,3.016423e+09,3.169741e+09,3.339906e+09,3.526757e+09,3.830200e+09,4.172952e+09,4.203822e+09

In [100]:
# 4 Conver the table from wide to long format
CAINC1_df = CAINC1_df.melt(id_vars=['FIPS5', 'geographic_area_name'], 
                            var_name='year',
                            value_name='personal_income')
CAINC1_df['year'] = CAINC1_df['year'].astype(int)
CAINC1_df['personal_income'] = CAINC1_df['personal_income'].astype(float)
CAINC1_df = CAINC1_df.sort_values(by=['FIPS5', 'year']).reset_index(drop=True)
CAINC1_df

         FIPS5 geographic_area_name  year  personal_income
0        00000        United States  1980     2.313972e+09
1        00000        United States  1981     2.590995e+09
2        00000        United States  1982     2.777640e+09
3        00000        United States  1983     2.969333e+09
4        00000        United States  1984     3.275415e+09
...        ...                  ...   ...              ...
137595   98000             Far West  2018     3.339906e+09
137596   98000             Far West  2019     3.526757e+09
137597   98000             Far West  2020     3.830200e+09
137598   98000             Far West  2021     4.172952e+09
137599   98000             Far West  2022     4.203822e+09

[137600 rows x 4 columns]

In [101]:
CAINC1_df['year'].value_counts()

year
1980    3200
2012    3200
2004    3200
2005    3200
2006    3200
2007    3200
2008    3200
2009    3200
2010    3200
2011    3200
2013    3200
2002    3200
2014    3200
2015    3200
2016    3200
2017    3200
2018    3200
2019    3200
2020    3200
2021    3200
2003    3200
2001    3200
1981    3200
1990    3200
1982    3200
1983    3200
1984    3200
1985    3200
1986    3200
1987    3200
1988    3200
1989    3200
1991    3200
2000    3200
1992    3200
1993    3200
1994    3200
1995    3200
1996    3200
1997    3200
1998    3200
1999    3200
2022    3200
Name: count, dtype: int64

In [102]:
CAINC1_df.isna().sum()

FIPS5                      0
geographic_area_name       0
year                       0
personal_income         1294
dtype: int64

In [103]:
# 5. Merge the two dataframes on FIPS5 and year
merged_bea_df = pd.merge(CAGDP1_df, CAINC1_df, on=['FIPS5', 'year'], how='outer', suffixes=(None, '_y'))
merged_bea_df = merged_bea_df.drop(columns=[col for col in merged_bea_df.columns if col.endswith('_y')])
merged_bea_df

         FIPS5 geographic_area_name  year          rgdp  personal_income
0        00000                  NaN  1980           NaN     2.313972e+09
1        00000                  NaN  1981           NaN     2.590995e+09
2        00000                  NaN  1982           NaN     2.777640e+09
3        00000                  NaN  1983           NaN     2.969333e+09
4        00000                  NaN  1984           NaN     3.275415e+09
...        ...                  ...   ...           ...              ...
137595   98000             Far West  2018  3.956948e+09     3.339906e+09
137596   98000             Far West  2019  4.115306e+09     3.526757e+09
137597   98000             Far West  2020  4.055844e+09     3.830200e+09
137598   98000             Far West  2021  4.352483e+09     4.172952e+09
137599   98000             Far West  2022  4.411936e+09     4.203822e+09

[137600 rows x 5 columns]

In [104]:
merged_bea_df.isna().sum()

FIPS5                       0
geographic_area_name    67684
year                        0
rgdp                    67807
personal_income          1294
dtype: int64

In [105]:
merged_bea_df['year'].value_counts()

year
1980    3200
2012    3200
2004    3200
2005    3200
2006    3200
2007    3200
2008    3200
2009    3200
2010    3200
2011    3200
2013    3200
2002    3200
2014    3200
2015    3200
2016    3200
2017    3200
2018    3200
2019    3200
2020    3200
2021    3200
2003    3200
2001    3200
1981    3200
1990    3200
1982    3200
1983    3200
1984    3200
1985    3200
1986    3200
1987    3200
1988    3200
1989    3200
1991    3200
2000    3200
1992    3200
1993    3200
1994    3200
1995    3200
1996    3200
1997    3200
1998    3200
1999    3200
2022    3200
Name: count, dtype: int64

In [106]:
# 6. Save the merged dataframe to a CSV file
OUTPUT_PATH = "/Users/koacow/BOSTON UNIVERSITY Dropbox/Ngoc Duy Khoa Cao/GLOB~S/Data/U.S. County Data/BEA_COUNTY_1969_2023/bea_county_income_gdp_1980_2022.csv"
merged_bea_df.to_csv(OUTPUT_PATH, index=False)