In [18]:
import pandas as pd

In [19]:
knowledge_div_df = pd.read_csv('data/knowledge_div via entropy.csv')
knowledge_div_df

/var/folders/zx/x6hb1_p95p33hh3235qrnlqm0000gn/T/ipykernel_64981/2352064664.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  knowledge_div_df = pd.read_csv('data/knowledge_div via entropy.csv')

        citing_patent_id  entropy_score
0               10000000       1.039721
1               10000001      -0.000000
2               10000002       1.627269
3               10000003       0.881594
4               10000004       0.997282
...                  ...            ...
7738356          RE50353       1.050309
7738357          RE50354       1.126929
7738358          RE50355       1.465029
7738359          RE50356       1.634369
7738360          RE50357       1.235145

[7738361 rows x 2 columns]

In [20]:
main_df = pd.read_csv('./data/patents_innovation_measures_no_knowledge_diversity.csv')
main_df

/var/folders/zx/x6hb1_p95p33hh3235qrnlqm0000gn/T/ipykernel_64981/790933186.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  main_df = pd.read_csv('./data/patents_innovation_measures_no_knowledge_diversity.csv')

,patent_id,atypicality_score,tech_leap_score,fwd_citation_impact_score
0,10000000,NaN,0.500000,18.195203
1,10000001,8.984207,0.500000,NaN
2,10000002,8.375340,0.666667,NaN
3,10000003,6.990229,0.600000,1.386294
4,10000004,6.239670,0.666667,NaN
...,...,...,...,...
7507814,RE50254,NaN,NaN,NaN
7507815,RE50255,NaN,NaN,NaN
7507816,RE50256,NaN,NaN,NaN
7507817,RE50257,NaN,NaN,NaN
7507818,RE50258,NaN,NaN,NaN

In [27]:
knowledge_div_df['citing_patent_id'].duplicated().sum()

13

In [22]:
main_df['patent_id'].duplicated().sum()

0

In [23]:
main_df = main_df.merge(knowledge_div_df, left_on='patent_id', right_on='citing_patent_id', how='left')
main_df = main_df.drop(columns=['citing_patent_id'])
main_df

,patent_id,atypicality_score,tech_leap_score,fwd_citation_impact_score,entropy_score
0,10000000,NaN,0.500000,18.195203,1.039721
1,10000001,8.984207,0.500000,NaN,-0.000000
2,10000002,8.375340,0.666667,NaN,1.627269
3,10000003,6.990229,0.600000,1.386294,0.881594
4,10000004,6.239670,0.666667,NaN,0.997282
...,...,...,...,...,...
7507826,RE50254,NaN,NaN,NaN,NaN
7507827,RE50255,NaN,NaN,NaN,1.329977
7507828,RE50256,NaN,NaN,NaN,NaN
7507829,RE50257,NaN,NaN,NaN,NaN
7507830,RE50258,NaN,NaN,NaN,-0.000000

In [14]:
import pandas as pd
final_fwdcitations = pd.read_csv('./data/final_fwdcitation.csv')
main_df = pd.read_csv('/Users/koacow/BOSTON UNIVERSITY Dropbox/Ngoc Duy Khoa Cao/GLOB~S/Research Projects/Shocks and Innovation/Patent Data/Innovation Measures/patents_innovation_measures.csv')

/var/folders/zx/x6hb1_p95p33hh3235qrnlqm0000gn/T/ipykernel_78485/4221269648.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  final_fwdcitations = pd.read_csv('./data/final_fwdcitation.csv')
/var/folders/zx/x6hb1_p95p33hh3235qrnlqm0000gn/T/ipykernel_78485/4221269648.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  main_df = pd.read_csv('/Users/koacow/BOSTON UNIVERSITY Dropbox/Ngoc Duy Khoa Cao/GLOB~S/Research Projects/Shocks and Innovation/Patent Data/Innovation Measures/patents_innovation_measures.csv')

In [15]:
main_df = main_df.merge(final_fwdcitations, on='patent_id', how='right')
main_df

,patent_id,atypicality_score,tech_leap_score,fwd_citation_impact_score,entropy_score,patent_type,patent_date,patent_title,wipo_kind,forward_citations
0,10000000,NaN,0.500000,18.195203,1.039721,utility,2018-06-19,Coherent LADAR using intra-pixel quadrature de...,B2,13
1,10000001,8.984207,0.500000,NaN,-0.000000,utility,2018-06-19,Injection molding machine and mold thickness c...,B2,0
2,10000002,8.375340,0.666667,NaN,1.627269,utility,2018-06-19,Method for manufacturing polymer film and co-e...,B2,0
3,10000003,6.990229,0.600000,1.386294,0.881594,utility,2018-06-19,Method for producing a container from a thermo...,B2,2
4,10000004,6.239670,0.666667,NaN,0.997282,utility,2018-06-19,"Process of obtaining a double-oriented film, c...",B2,0
...,...,...,...,...,...,...,...,...,...,...
7507826,RE50254,NaN,NaN,NaN,NaN,reissue,2024-12-31,Electrode assembly including electrode plates ...,E1,0
7507827,RE50255,NaN,NaN,NaN,1.329977,reissue,2024-12-31,Mobile terminal,E1,0
7507828,RE50256,NaN,NaN,NaN,NaN,reissue,2024-12-31,"Oscillation circuit, oscillator, electronic ap...",E1,0
7507829,RE50257,NaN,NaN,NaN,NaN,reissue,2024-12-31,Data processing device and data processing method,E1,0
7507830,RE50258,NaN,NaN,NaN,-0.000000,reissue,2024-12-31,Projection device,E1,0

In [16]:
main_df = main_df.drop_duplicates(subset=['patent_id'], keep='first')
main_df

,patent_id,atypicality_score,tech_leap_score,fwd_citation_impact_score,entropy_score,patent_type,patent_date,patent_title,wipo_kind,forward_citations
0,10000000,NaN,0.500000,18.195203,1.039721,utility,2018-06-19,Coherent LADAR using intra-pixel quadrature de...,B2,13
1,10000001,8.984207,0.500000,NaN,-0.000000,utility,2018-06-19,Injection molding machine and mold thickness c...,B2,0
2,10000002,8.375340,0.666667,NaN,1.627269,utility,2018-06-19,Method for manufacturing polymer film and co-e...,B2,0
3,10000003,6.990229,0.600000,1.386294,0.881594,utility,2018-06-19,Method for producing a container from a thermo...,B2,2
4,10000004,6.239670,0.666667,NaN,0.997282,utility,2018-06-19,"Process of obtaining a double-oriented film, c...",B2,0
...,...,...,...,...,...,...,...,...,...,...
7507826,RE50254,NaN,NaN,NaN,NaN,reissue,2024-12-31,Electrode assembly including electrode plates ...,E1,0
7507827,RE50255,NaN,NaN,NaN,1.329977,reissue,2024-12-31,Mobile terminal,E1,0
7507828,RE50256,NaN,NaN,NaN,NaN,reissue,2024-12-31,"Oscillation circuit, oscillator, electronic ap...",E1,0
7507829,RE50257,NaN,NaN,NaN,NaN,reissue,2024-12-31,Data processing device and data processing method,E1,0
7507830,RE50258,NaN,NaN,NaN,-0.000000,reissue,2024-12-31,Projection device,E1,0

In [17]:
main_df.to_csv('/Users/koacow/BOSTON UNIVERSITY Dropbox/Ngoc Duy Khoa Cao/GLOB~S/Research Projects/Shocks and Innovation/Patent Data/Innovation Measures/patents_innovation_measures.csv', index=False)